'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {apiFetch,readToken} from '../../lib/api';
interface Preview {periodLabel:string;distributableAmount:number;totalShares:number;allocations:{memberId:string;memberNo:number;memberName:string;shareBalance:number;amount:number}[]}
interface Run {id:string;periodLabel:string;distributableAmount:number;memberCount:number}
const money=(amount:number)=>'₦'+Number(amount).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
export default function DividendsPage(){
 const router=useRouter();const [year,setYear]=useState(String(new Date().getUTCFullYear())),[amount,setAmount]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[runs,setRuns]=useState<Run[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
 useEffect(()=>{const token=readToken();if(!token){router.replace('/login');return;}let active=true;apiFetch<Run[]>('/dividends',token).then(data=>{if(active)setRuns(data);}).catch(err=>{if(active)setError(err instanceof Error?err.message:'Cannot load dividend runs');});return()=>{active=false;};},[router]);
 async function showPreview(){const token=readToken();if(!token){router.replace('/login');return;}setBusy(true);setError(null);setNotice(null);setPreview(null);try{setPreview(await apiFetch<Preview>('/dividends/preview?period='+encodeURIComponent(year)+'&amount='+encodeURIComponent(amount),token));}catch(err){setError(err instanceof Error?err.message:'Preview failed');}finally{setBusy(false);}}
 async function post(){const token=readToken();if(!token||!preview)return;if(!confirm('Post '+money(preview.distributableAmount)+' of dividends for '+preview.periodLabel+'? Allocations use share balances at posting.'))return;setBusy(true);setError(null);setNotice(null);try{const result=await apiFetch<{runId:string;periodLabel:string;total:number;members:number;entryNo:number}>('/dividends/post',token,{method:'POST',body:JSON.stringify({periodLabel:preview.periodLabel,distributableAmount:preview.distributableAmount})});setNotice('Posted '+money(result.total)+' to '+result.members+' member(s) for '+result.periodLabel+' (journal #'+result.entryNo+').');setPreview(null);setRuns(await apiFetch<Run[]>('/dividends',token));}catch(err){setError(err instanceof Error?err.message:'Posting failed');}finally{setBusy(false);}}
 return <main style={{maxWidth:1000,margin:'0 auto',padding:28}}><Link href='/'>← Dashboard</Link><h1>Dividends</h1><p>Preview a share-based distribution, then credit members’ savings. Each cooperative can post once per year. Allocations use share balances at posting, which may differ from the preview.</p><div className='card' style={{display:'flex',gap:12,flexWrap:'wrap',alignItems:'end'}}><label style={{display:"grid",gap:4,maxWidth:"100%"}}>Year<input style={{width:180,maxWidth:"100%",boxSizing:"border-box"}} aria-label='Dividend year' value={year} maxLength={4} disabled={busy} onChange={e=>{setYear(e.target.value);setPreview(null);}}/></label><label style={{display:"grid",gap:4,maxWidth:"100%"}}>Distributable amount (₦)<input style={{width:220,maxWidth:"100%",boxSizing:"border-box"}} aria-label='Distributable amount' type='number' min='0.01' max='100000000000' step='0.01' value={amount} disabled={busy} onChange={e=>{setAmount(e.target.value);setPreview(null);}}/></label><button className='btn' disabled={busy||!amount} onClick={()=>void showPreview()}>Preview dividends</button><button className='btn secondary' disabled={busy||!preview} onClick={()=>void post()}>Post dividends</button></div>{error&&<p role='alert' style={{color:'#b42318'}}>{error}</p>}{notice&&<p role='status' style={{color:'#067647'}}>{notice}</p>}{busy&&<p role='status'>Checking dividend request…</p>}
 {preview&&<section className='card' style={{overflowX:'auto'}}><h2>Preview for {preview.periodLabel}</h2><p>Total {money(preview.distributableAmount)} · Share capital {money(preview.totalShares)}</p><table className='data'><thead><tr><th>Member</th><th>Share balance</th><th>Dividend</th></tr></thead><tbody>{preview.allocations.map(a=><tr key={a.memberId}><td>{a.memberName} (#{a.memberNo})</td><td>{money(a.shareBalance)}</td><td>{money(a.amount)}</td></tr>)}</tbody></table></section>}
 <section className='card' style={{marginTop:16,overflowX:'auto'}}><h2>Posted dividend runs</h2>{runs.length===0?<p>No posted runs.</p>:<table className='data'><thead><tr><th>Year</th><th>Total</th><th>Members credited</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td>{r.periodLabel}</td><td>{money(r.distributableAmount)}</td><td>{r.memberCount}</td></tr>)}</tbody></table>}</section></main>;
}
