'use client';
import {FormEvent,useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {apiFetch,readToken} from '../../lib/api';
interface Batch {id:string;filename:string;status:string;valid_rows:number;total_amount:string}
interface Preview {batchId:string;filename:string;totals:{totalRows:number;valid:number;invalid:number;totalAmount:number};errors:{row:number;reason:string}[]}
export default function PayrollPage(){
 const router=useRouter(),[batches,setBatches]=useState<Batch[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
 const [filename,setFilename]=useState(''),[csv,setCsv]=useState(''),[preview,setPreview]=useState<Preview|null>(null);
 async function upload(event:FormEvent){event.preventDefault();const token=readToken();if(!token)return;setBusy(true);setError(null);setNotice(null);setPreview(null);try{const result=await apiFetch<Preview>('/payroll/import/preview',token,{method:'POST',body:JSON.stringify({filename,csv})});setPreview(result);setNotice('The original upload preview was acknowledged. Review validation and the current batch register before submission.');await refresh();}catch(err){setError(err instanceof Error?err.message:'Preview failed');}finally{setBusy(false);}}
 async function chooseFile(file?:File){if(!file)return;if(file.size>16000){setError('Choose a CSV file no larger than 16 KB for this upload.');return;}try{setFilename(file.name);setCsv(await file.text());setError(null);}catch{setError('Cannot read this file. Choose it again or paste the CSV.');}}
 async function refresh(){const token=readToken();if(!token){router.replace('/login');return;}setBatches(await apiFetch<Batch[]>('/payroll/batches',token));}
 useEffect(()=>{void refresh().catch(err=>setError(err instanceof Error?err.message:'Cannot load batches'));},[]);
 async function submit(batch:Batch){const token=readToken();if(!token)return;if(!confirm('Submit '+batch.filename+' for approval? Submission does not post money.'))return;setBusy(true);setError(null);setNotice(null);try{await apiFetch('/payroll/import/commit',token,{method:'POST',body:JSON.stringify({batchId:batch.id})});setNotice('The original submission was acknowledged. The register shows the current batch status; a different user must approve posting.');await refresh();}catch(err){setError(err instanceof Error?err.message:'Submission failed');}finally{setBusy(false);}}
 return <main style={{maxWidth:1000,padding:28,margin:'0 auto'}}><Link href='/'>← Dashboard</Link><h1>Payroll submissions</h1><p>Upload a CSV with memberNo and amount columns. This preview supports savings deductions only. Preview and submission do not move money; a different user must approve posting.</p>
 <form className='card' onSubmit={upload} style={{marginBottom:16}}><h2>Prepare an upload preview</h2><label htmlFor='payroll-file'>CSV file (up to 16 KB)</label><input id='payroll-file' type='file' accept='.csv,text/csv' disabled={busy} onChange={event=>void chooseFile(event.target.files?.[0])}/><p><label htmlFor='payroll-filename'>Filename</label><input id='payroll-filename' required maxLength={255} value={filename} disabled={busy} onChange={event=>setFilename(event.target.value)}/></p><p><label htmlFor='payroll-csv'>CSV contents</label><textarea id='payroll-csv' required maxLength={16000} rows={7} value={csv} disabled={busy} onChange={event=>setCsv(event.target.value)} style={{display:'block',width:'100%',boxSizing:'border-box'}} placeholder={'memberNo,amount\n1,0.23'}/></p><p>If a request times out, use Recover original request. Keep its original filename and CSV until acknowledged. A new upload after acknowledgement creates a separate batch.</p><button className='btn' disabled={busy||!filename.trim()||!csv.trim()} type='submit'>Create upload preview</button></form>
 {error&&<p role='alert'>{error}</p>}{notice&&<p role='status'>{notice}</p>}{preview&&<section aria-label='Upload validation results' className='card'><h2>Upload validation results</h2><p>{preview.filename} · Batch {preview.batchId}</p><p>{preview.totals.totalRows} rows · {preview.totals.valid} valid · {preview.totals.invalid} invalid · ₦{preview.totals.totalAmount}</p>{preview.errors.length>0?<ul>{preview.errors.map((issue,index)=><li key={index}>Row/reference {issue.row}: {issue.reason}</li>)}</ul>:<p>No validation errors.</p>}</section>}
 <button className='btn secondary' disabled={busy} onClick={()=>void refresh().catch(err=>setError(String(err)))}>Refresh batches</button><div className='card' style={{overflowX:'auto',marginTop:16}}>{batches.length===0?<p>No prepared payroll batches.</p>:<table className='data'><thead><tr><th>File</th><th>Status</th><th>Valid rows</th><th>Total (₦)</th><th>Action</th></tr></thead><tbody>{batches.map(batch=><tr key={batch.id}><td>{batch.filename}</td><td>{batch.status}</td><td>{batch.valid_rows}</td><td>{batch.total_amount}</td><td>{batch.status==='PREVIEWED'?<button className='btn' disabled={busy||batch.valid_rows===0} aria-label={'Submit '+batch.filename} onClick={()=>void submit(batch)}>Submit for approval</button>:'—'}</td></tr>)}</tbody></table>}</div></main>;
}
