import { Inject, Injectable, NotFoundException } from '@nestjs/common';
import { Pool } from 'pg';
import PDFDocument from 'pdfkit';
import { withTenant } from '@coopengine/db';
import { DB_POOL } from '../database/database.module';

/** ₦1,234,567.89 — grouping is not cosmetic when a treasurer reads a statement. */
export function money(value: number | string | null | undefined): string {
  const n = Number(value ?? 0);
  const safe = Number.isFinite(n) ? n : 0;
  const magnitude = Math.abs(safe).toLocaleString('en-NG', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
  // ledgers print the sign in front of the symbol: -₦2,500.00
  return `${safe < 0 ? '-' : ''}₦${magnitude}`;
}

interface Column {
  label: string;
  width: number;
  align?: 'left' | 'right';
}

@Injectable()
export class PdfService {
  constructor(@Inject(DB_POOL) private readonly pool: Pool) {}

  // --------------------------------------------------------------- primitives

  private doc(): PDFKit.PDFDocument {
    return new PDFDocument({ size: 'A4', margin: 40, bufferPages: true });
  }

  private collect(doc: PDFKit.PDFDocument): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);
    });
  }

  private header(doc: PDFKit.PDFDocument, orgName: string, title: string, subtitle?: string): void {
    doc.fontSize(15).fillColor('#12324a').text(orgName, { continued: false });
    doc.moveDown(0.2);
    doc.fontSize(12).fillColor('#111111').text(title);
    if (subtitle) {
      doc.fontSize(9).fillColor('#5b6772').text(subtitle);
    }
    doc.moveDown(0.4);
    doc
      .moveTo(40, doc.y)
      .lineTo(555, doc.y)
      .strokeColor('#cfd6de')
      .stroke();
    doc.moveDown(0.6);
    doc.fillColor('#111111');
  }

  private footer(doc: PDFKit.PDFDocument): void {
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i += 1) {
      doc.switchToPage(i);
      doc.fontSize(8).fillColor('#7a848c');
      doc.text(
        `Generated by Co-opEngine · ${new Date().toISOString().slice(0, 19).replace('T', ' ')} UTC · page ${i + 1} of ${range.count}`,
        40,
        doc.page.height - 34,
        { width: 515, align: 'center' },
      );
    }
  }

  private table(doc: PDFKit.PDFDocument, columns: Column[], rows: (string | number)[][]): void {
    const startX = 40;
    const rowHeight = 16;
    const drawRow = (cells: (string | number)[], bold = false): void => {
      if (doc.y + rowHeight > doc.page.height - 60) {
        doc.addPage();
        this.tableHeaderRow(doc, columns, startX, bold);
      }
      const y = doc.y;
      let x = startX;
      doc.fontSize(8.5).font(bold ? 'Helvetica-Bold' : 'Helvetica');
      columns.forEach((col, idx) => {
        doc.text(String(cells[idx] ?? ''), x, y, {
          width: col.width,
          align: col.align ?? 'left',
        });
        x += col.width;
      });
      doc.y = y + rowHeight;
      if (bold) {
        doc
          .moveTo(startX, doc.y - 3)
          .lineTo(startX + columns.reduce((s, c) => s + c.width, 0), doc.y - 3)
          .strokeColor('#cfd6de')
          .stroke();
      }
    };

    this.tableHeaderRow(doc, columns, startX, true);
    rows.forEach((cells) => drawRow(cells));
    doc.font('Helvetica');
  }

  private tableHeaderRow(
    doc: PDFKit.PDFDocument,
    columns: Column[],
    startX: number,
    _emphasis: boolean,
  ): void {
    const y = doc.y;
    let x = startX;
    doc.fontSize(8.5).font('Helvetica-Bold').fillColor('#12324a');
    columns.forEach((col) => {
      doc.text(col.label, x, y, { width: col.width, align: col.align ?? 'left' });
      x += col.width;
    });
    doc.y = y + 15;
    doc
      .moveTo(startX, doc.y - 3)
      .lineTo(startX + columns.reduce((s, c) => s + c.width, 0), doc.y - 3)
      .strokeColor('#12324a')
      .stroke();
    doc.fillColor('#111111').font('Helvetica');
  }

  private async orgName(orgId: string): Promise<string> {
    const res = await this.pool.query(`SELECT name FROM organizations WHERE id = $1`, [orgId]);
    return (res.rows[0] as { name?: string } | undefined)?.name ?? 'Cooperative';
  }

  // ---------------------------------------------------------------- documents

  /** Member savings statement: opening balance, transactions, closing balance. */
  async memberStatement(
    orgId: string,
    memberId: string,
    from?: string,
    to?: string,
  ): Promise<{ buffer: Buffer; filename: string }> {
    const data = await withTenant(this.pool, orgId, async (c) => {
      const member = await c.query(
        `SELECT member_no, first_name, last_name, status, phone, email
           FROM members WHERE id = $1`,
        [memberId],
      );
      if (!member.rows[0]) throw new NotFoundException('Member not found');
      const account = await c.query(
        `SELECT id, account_no, current_balance FROM member_savings_accounts
          WHERE member_id = $1 ORDER BY created_at LIMIT 1`,
        [memberId],
      );
      const accountRow = account.rows[0] as
        | { id: string; account_no: string; current_balance: string }
        | undefined;
      const txns = accountRow
        ? await c.query(
            `SELECT t.type, t.signed_amount, t.running_balance,
                    je.description, t.created_at
               FROM savings_transactions t
               LEFT JOIN journal_entries je ON je.id = t.journal_entry_id
              WHERE t.account_id = $1
                AND ($2::date IS NULL OR t.created_at::date >= $2::date)
                AND ($3::date IS NULL OR t.created_at::date <= $3::date)
              ORDER BY t.created_at`,
            [accountRow.id, from ?? null, to ?? null],
          )
        : { rows: [] };
      return {
        member: member.rows[0] as {
          member_no: number;
          first_name: string;
          last_name: string;
          status: string;
          phone: string | null;
          email: string | null;
        },
        account: accountRow,
        txns: txns.rows as {
          type: string;
          signed_amount: string;
          running_balance: string;
          description: string | null;
          created_at: Date;
        }[],
      };
    });

    const orgName = await this.orgName(orgId);
    const doc = this.doc();
    const buffer = this.collect(doc);

    const member = data.member;
    this.header(
      doc,
      orgName,
      'Member savings statement',
      `Member ${member.member_no} · ${member.first_name} ${member.last_name}` +
        (data.account ? ` · account ${data.account.account_no}` : '') +
        (from || to ? ` · ${from ?? 'start'} to ${to ?? 'today'}` : ' · all transactions'),
    );

    const first = data.txns[0];
    const opening = first
      ? Number(first.running_balance) - Number(first.signed_amount)
      : Number(data.account?.current_balance ?? 0);

    doc.fontSize(9.5);
    doc.text(`Opening balance: ${money(opening)}`);
    doc.text(`Closing balance: ${money(data.account?.current_balance ?? 0)}`);
    doc.moveDown(0.6);

    this.table(
      doc,
      [
        { label: 'Date', width: 70 },
        { label: 'Type', width: 85 },
        { label: 'Description', width: 175 },
        { label: 'Amount', width: 90, align: 'right' },
        { label: 'Balance', width: 95, align: 'right' },
      ],
      data.txns.map((t) => [
        new Date(t.created_at).toISOString().slice(0, 10),
        t.type.replace('_', ' '),
        (t.description ?? '').slice(0, 46),
        money(t.signed_amount),
        money(t.running_balance),
      ]),
    );

    if (!data.txns.length) doc.fontSize(9).fillColor('#7a848c').text('No transactions in this period.');
    doc.fillColor('#111111');
    doc.moveDown(0.8);
    doc.fontSize(9).text(`Transactions shown: ${data.txns.length}`, { align: 'left' });
    doc.moveDown(1.2);
    doc.fontSize(8).fillColor('#7a848c').text('Member status: ' + member.status);
    if (member.phone) doc.text(`Phone: ${member.phone}`);

    this.footer(doc);
    doc.end();
    return {
      buffer: await buffer,
      filename: `statement-${member.member_no}-${new Date().toISOString().slice(0, 10)}.pdf`,
    };
  }

  /** Loan schedule with what has been paid and what is outstanding. */
  async loanStatement(orgId: string, loanId: string): Promise<{ buffer: Buffer; filename: string }> {
    const data = await withTenant(this.pool, orgId, async (c) => {
      const loan = await c.query(
        `SELECT l.id, l.principal, l.outstanding_principal, l.interest_rate_pa, l.term_months,
                l.interest_method, l.status, l.created_at,
                m.member_no, m.first_name, m.last_name
           FROM loans l JOIN members m ON m.id = l.member_id
          WHERE l.id = $1`,
        [loanId],
      );
      if (!loan.rows[0]) throw new NotFoundException('Loan not found');
      const instalments = await c.query(
        `SELECT seq, due_date, principal_due, interest_due, paid_principal, paid_interest
           FROM loan_repayments WHERE loan_id = $1 ORDER BY seq`,
        [loanId],
      );
      return { loan: loan.rows[0], instalments: instalments.rows };
    });

    const orgName = await this.orgName(orgId);
    const doc = this.doc();
    const buffer = this.collect(doc);
    const loan = data.loan as {
      principal: string;
      outstanding_principal: string;
      interest_rate_pa: string;
      term_months: number;
      interest_method: string;
      status: string;
      member_no: number;
      first_name: string;
      last_name: string;
    };

    this.header(
      doc,
      orgName,
      'Loan statement',
      `Member ${loan.member_no} · ${loan.first_name} ${loan.last_name} · ${loan.status}`,
    );
    doc.fontSize(9.5);
    doc.text(`Principal: ${money(loan.principal)}`);
    doc.text(`Outstanding: ${money(loan.outstanding_principal)}`);
    doc.text(`Rate: ${Number(loan.interest_rate_pa).toFixed(2)}% p.a. · ${loan.term_months} months · ${loan.interest_method}`);
    doc.moveDown(0.6);

    const today = new Date().toISOString().slice(0, 10);
    const rows = (data.instalments as {
      seq: number;
      due_date: Date;
      principal_due: string;
      interest_due: string;
      paid_principal: string;
      paid_interest: string;
    }[]).map((r) => {
      const paid = Number(r.paid_principal) + Number(r.paid_interest) > 0;
      const due = new Date(r.due_date).toISOString().slice(0, 10);
      const status = paid
        ? 'PAID'
        : due < today
          ? 'OVERDUE'
          : 'PENDING';
      return [
        r.seq,
        due,
        money(r.principal_due),
        money(r.interest_due),
        money(Number(r.paid_principal) + Number(r.paid_interest)),
        status,
      ];
    });

    this.table(
      doc,
      [
        { label: '#', width: 30 },
        { label: 'Due date', width: 80 },
        { label: 'Principal', width: 95, align: 'right' },
        { label: 'Interest', width: 95, align: 'right' },
        { label: 'Paid', width: 95, align: 'right' },
        { label: 'Status', width: 80 },
      ],
      rows,
    );

    this.footer(doc);
    doc.end();
    return {
      buffer: await buffer,
      filename: `loan-${loan.member_no}-${new Date().toISOString().slice(0, 10)}.pdf`,
    };
  }

  /** Board pack: the monthly committee summary. */
  async boardPack(orgId: string, periodCode: string): Promise<{ buffer: Buffer; filename: string }> {
    const data = await withTenant(this.pool, orgId, async (c) => {
      const members = await c.query(
        `SELECT status, count(*)::int AS n FROM members GROUP BY status ORDER BY status`,
      );
      const savings = await c.query(
        `SELECT coalesce(sum(current_balance), 0) AS total,
                count(*)::int AS accounts
           FROM member_savings_accounts WHERE status = 'ACTIVE'`,
      );
      const shares = await c.query(
        `SELECT coalesce(sum(current_balance), 0) AS total FROM member_share_accounts`,
      );
      const loans = await c.query(
        `SELECT coalesce(sum(outstanding_principal), 0) AS total,
                count(*)::int AS live
           FROM loans WHERE status IN ('DISBURSED','DEFAULTED')`,
      );
      const arrears = await c.query(
        `SELECT
           count(*) FILTER (WHERE now()::date - r.due_date BETWEEN 1 AND 30)  AS b1,
           count(*) FILTER (WHERE now()::date - r.due_date BETWEEN 31 AND 60) AS b2,
           count(*) FILTER (WHERE now()::date - r.due_date BETWEEN 61 AND 90) AS b3,
           count(*) FILTER (WHERE now()::date - r.due_date > 90)              AS b4
         FROM loan_repayments r JOIN loans l ON l.id = r.loan_id
        WHERE l.status IN ('DISBURSED','DEFAULTED')
          AND r.due_date < now()::date
          AND coalesce(r.paid_principal, 0) < r.principal_due`,
      );
      const dividends = await c.query(
        `SELECT coalesce(sum(distributable_amount), 0) AS total
           FROM dividend_runs WHERE period_label = $1`,
        [periodCode],
      ).catch(() => ({ rows: [{ total: '0' }] }));
      const tb = await c.query(
        `SELECT coalesce(sum(jl.debit - jl.credit), 0) AS net
           FROM journal_lines jl JOIN journal_entries je ON je.id = jl.journal_entry_id
          WHERE je.status = 'POSTED'`,
      );
      const period = await c.query(
        `SELECT status FROM ledger_periods WHERE code = $1`,
        [periodCode],
      );
      return {
        members: members.rows as { status: string; n: number }[],
        savings: savings.rows[0] as { total: string; accounts: number },
        shares: shares.rows[0] as { total: string },
        loans: loans.rows[0] as { total: string; live: number },
        arrears: arrears.rows[0] as { b1: number; b2: number; b3: number; b4: number },
        dividends: dividends.rows[0] as { total: string },
        net: (tb.rows[0] as { net: string }).net,
        period: period.rows[0] as { status: string } | undefined,
      };
    });

    const orgName = await this.orgName(orgId);
    const doc = this.doc();
    const buffer = this.collect(doc);

    this.header(
      doc,
      orgName,
      `Board pack — ${periodCode}`,
      `Period status: ${data.period?.status ?? 'not created'} · prepared ${new Date().toISOString().slice(0, 10)}`,
    );

    const section = (title: string, lines: [string, string][]): void => {
      doc.moveDown(0.5).fontSize(10.5).fillColor('#12324a').text(title);
      doc.moveDown(0.2).fillColor('#111111').fontSize(9);
      lines.forEach(([k, v]) => doc.text(`${k}: ${v}`));
      doc.moveDown(0.3);
    };

    section('Membership', data.members.map((m) => [m.status, String(m.n)] as [string, string]));
    section('Savings', [
      ['Total member savings', money(data.savings.total)],
      ['Active savings accounts', String(data.savings.accounts)],
    ]);
    section('Share capital', [['Total share capital', money(data.shares.total)]]);
    section('Loan book', [
      ['Outstanding principal', money(data.loans.total)],
      ['Live loans', String(data.loans.live)],
    ]);
    section('Arrears ageing (instalments)', [
      ['1–30 days', String(data.arrears.b1)],
      ['31–60 days', String(data.arrears.b2)],
      ['61–90 days', String(data.arrears.b3)],
      ['over 90 days', String(data.arrears.b4)],
    ]);
    section('Dividends', [['Declared for this period', money(data.dividends.total)]]);
    section('Books', [
      ['Trial balance net (must be 0)', money(data.net)],
      ['Balanced', Math.abs(Number(data.net)) < 0.005 ? 'yes' : 'NO — investigate'],
    ]);

    this.footer(doc);
    doc.end();
    return { buffer: await buffer, filename: `board-pack-${periodCode}.pdf` };
  }

  /** Counter receipt for a savings transaction. */
  async receipt(orgId: string, transactionId: string): Promise<{ buffer: Buffer; filename: string }> {
    const data = await withTenant(this.pool, orgId, async (c) => {
      const res = await c.query(
        `SELECT t.id, t.type, t.signed_amount, t.running_balance,
                je.description, t.created_at,
                a.account_no, m.member_no, m.first_name, m.last_name
           FROM savings_transactions t
           JOIN member_savings_accounts a ON a.id = t.account_id
           JOIN members m ON m.id = a.member_id
           LEFT JOIN journal_entries je ON je.id = t.journal_entry_id
          WHERE t.id = $1`,
        [transactionId],
      );
      if (!res.rows[0]) throw new NotFoundException('Transaction not found');
      return res.rows[0] as {
        type: string;
        signed_amount: string;
        running_balance: string;
        description: string | null;
        created_at: Date;
        account_no: string;
        member_no: number;
        first_name: string;
        last_name: string;
      };
    });

    const orgName = await this.orgName(orgId);
    const doc = this.doc();
    const buffer = this.collect(doc);

    this.header(doc, orgName, 'Transaction receipt', `Reference ${transactionId.slice(0, 8).toUpperCase()}`);
    doc.fontSize(10);
    doc.text(`Member: ${data.member_no} · ${data.first_name} ${data.last_name}`);
    doc.text(`Account: ${data.account_no}`);
    doc.text(`Date: ${new Date(data.created_at).toISOString().slice(0, 19).replace('T', ' ')}`);
    doc.moveDown(0.4);
    doc.fontSize(13).text(`${data.type.replace('_', ' ')}  ${money(data.signed_amount)}`);
    doc.fontSize(9).fillColor('#5b6772').text(`Balance after this transaction: ${money(data.running_balance)}`);
    doc.fillColor('#111111');
    if (data.description) doc.text(`Note: ${data.description}`);
    doc.moveDown(1.5);
    doc.fontSize(8).fillColor('#7a848c').text('Signature: ____________________________');

    this.footer(doc);
    doc.end();
    return {
      buffer: await buffer,
      filename: `receipt-${transactionId.slice(0, 8)}.pdf`,
    };
  }
}
