import 'reflect-metadata';
import {createHash,randomUUID} from 'node:crypto';
import {INestApplication,ValidationPipe} from '@nestjs/common';
import {Test} from '@nestjs/testing';
import {Pool} from 'pg';
import {withTenant} from '@coopengine/db';
import request from 'supertest';
import {afterAll,beforeAll,describe,expect,it} from 'vitest';
import {AppModule} from '../src/app.module';
import {DividendsService} from '../src/dividends/dividends.service';
import {ADMIN_PASSWORD,TEST_DATABASE_URL,ensureRbacSeeded} from './helpers';
describe('exact dividend year receipts (PostgreSQL)',()=>{
 let app:INestApplication,pool:Pool,platform:string;
 beforeAll(async()=>{process.env.DATABASE_URL=TEST_DATABASE_URL;pool=new Pool({connectionString:TEST_DATABASE_URL});await ensureRbacSeeded(pool);const module=await Test.createTestingModule({imports:[AppModule]}).compile();app=module.createNestApplication();app.setGlobalPrefix('api/v1');app.useGlobalPipes(new ValidationPipe({whitelist:true,transform:true,forbidNonWhitelisted:true}));await app.init();platform=(await request(app.getHttpServer()).post('/api/v1/auth/login').send({email:'admin@coopengine.dev',password:ADMIN_PASSWORD}).expect(200)).body.tokens.accessToken;});
 afterAll(async()=>{await app?.close();await pool?.end();});
 async function fixture(shares:number[]=[3,1],open=true){
  const suffix=randomUUID().slice(0,8),email=`dividend-${suffix}@coopengine.test`;
  const org=(await request(app.getHttpServer()).post('/api/v1/organizations').set('Authorization',`Bearer ${platform}`).send({name:`Dividend ${suffix}`,slug:`dividend-${suffix}`,adminEmail:email,adminPassword:'DividendPass123!'}).expect(201)).body.id;
  const token=(await request(app.getHttpServer()).post('/api/v1/auth/login').send({email,password:'DividendPass123!'}).expect(200)).body.tokens.accessToken,auth={Authorization:`Bearer ${token}`};
  const tenant=<T>(fn:Parameters<typeof withTenant<T>>[2])=>withTenant(pool,org,fn);
  const actor=(await request(app.getHttpServer()).get('/api/v1/auth/me').set(auth).expect(200)).body.user.id as string;
  const members:string[]=[],accounts:string[]=[];
  for(const share of shares){const member=(await request(app.getHttpServer()).post('/api/v1/members').set(auth).send({firstName:'Dividend',lastName:'Synthetic'}).expect(201)).body.id;members.push(member);await request(app.getHttpServer()).post(`/api/v1/members/${member}/approve`).set(auth).expect(200);await request(app.getHttpServer()).post(`/api/v1/shares/member/${member}/purchases`).set(auth).send({amount:share,idempotencyKey:randomUUID()}).expect(201);if(open)accounts.push((await request(app.getHttpServer()).post(`/api/v1/savings/member/${member}/account`).set(auth).send({}).expect(201)).body.id);}
  const period='2026',post=(amount=1.15,year=period)=>request(app.getHttpServer()).post('/api/v1/dividends/post').set(auth).send({periodLabel:year,distributableAmount:amount});
  const snapshot=()=>tenant(async c=>{const tables=['member_savings_accounts','savings_transactions','dividend_runs','dividend_allocations','journal_entries','journal_lines','financial_write_receipts','audit_logs','notifications','org_counters'];const s:Record<string,Record<string,unknown>[]>= {};for(const table of tables)s[table]=(await c.query(`SELECT * FROM ${table} ORDER BY ${table==='org_counters'?'organization_id':'id'}`)).rows;return s;});
  const deposit=(amount:number,index=0)=>request(app.getHttpServer()).post(`/api/v1/savings/accounts/${accounts[index]}/deposits`).set(auth).send({amount,idempotencyKey:randomUUID()});
  const reconcile=()=>tenant(async c=>(await c.query(`SELECT a.current_balance,(SELECT coalesce(sum(signed_amount),0)::text FROM savings_transactions WHERE account_id=a.id) AS movements,(SELECT coalesce(sum(credit-debit),0)::text FROM journal_lines WHERE member_id=a.member_id AND account_id IN(SELECT id FROM chart_of_accounts WHERE code='2000')) AS liability FROM member_savings_accounts a ORDER BY a.member_id`)).rows);
  return {org,auth,actor,members,accounts,period,tenant,post,snapshot,deposit,reconcile};
 }
 it('concurrent same-year posts return one run and one exact original response',async()=>{const f=await fixture(),r=await Promise.all([f.post().expect(201),f.post().expect(201)]);expect(r[0].body).toEqual(r[1].body);expect(r[0].body.total).toBe(1.15);const s=await f.snapshot();expect(s.dividend_runs).toHaveLength(1);expect(s.dividend_allocations!.map(a=>a.amount).sort()).toEqual(['0.29','0.86']);expect(s.journal_entries!.filter(j=>j.source==='DIVIDEND')).toHaveLength(1);expect(s.financial_write_receipts!.filter(j=>j.action==='dividends.post')).toHaveLength(1);expect(s.notifications!.filter(j=>j.type==='DIVIDEND_PAID')).toHaveLength(2);await f.post().expect(201);expect(await f.snapshot()).toEqual(s);for(const a of await f.reconcile()){expect(a.current_balance).toBe(a.movements);expect(a.current_balance).toBe(a.liability);}});
 it('concurrent changed amounts conflict without a second distribution',async()=>{const f=await fixture(),r=await Promise.all([f.post(1.15),f.post(1.16)]);expect(r.map(x=>x.status).sort()).toEqual([201,409]);expect((await f.snapshot()).dividend_runs).toHaveLength(1);});
 it('completed replay ignores changed shares, balances and closed periods',async()=>{const f=await fixture(),original=(await f.post().expect(201)).body;await f.deposit(0.23).expect(201);await request(app.getHttpServer()).post(`/api/v1/shares/member/${f.members[0]}/purchases`).set(f.auth).send({amount:5,idempotencyKey:randomUUID()}).expect(201);await f.tenant(c=>c.query("UPDATE ledger_periods SET status='CLOSED'"));const s=await f.snapshot();expect((await f.post().expect(201)).body).toEqual(original);expect(await f.snapshot()).toEqual(s);});
 it('changed actor cannot replay another actor’s receipt',async()=>{const f=await fixture();await f.post().expect(201);const s=await f.snapshot();await expect(app.get(DividendsService).post(f.org,randomUUID(),f.period,1.15)).rejects.toThrow(/different details/);expect(await f.snapshot()).toEqual(s);});
 it('current grants gate completed receipt replay',async()=>{const f=await fixture();await f.post().expect(201);const s=await f.snapshot();await pool.query('DELETE FROM user_roles WHERE user_id=$1',[f.actor]);await f.post().expect(401);expect(await f.snapshot()).toEqual(s);});
 it('changed scope refuses before writes',async()=>{const f=await fixture(),s=await f.snapshot();await f.post().set('X-CoopEngine-Financial-Scope',`${randomUUID()}:${f.actor}`).expect(409);expect(await f.snapshot()).toEqual(s);});
 it('requires strict explicit year and supported two-place money',async()=>{const f=await fixture(),s=await f.snapshot();for(const periodLabel of [undefined,null,'','2026\n','2026 ','26',2026,{}])await request(app.getHttpServer()).post('/api/v1/dividends/post').set(f.auth).send({periodLabel,distributableAmount:1.15}).expect(400);for(const amount of [0,-1,1.001,100000000001])await f.post(amount).expect(400);expect(await f.snapshot()).toEqual(s);});
 it('refused first attempt leaves no receipt and succeeds after reopening',async()=>{const f=await fixture();await f.tenant(c=>c.query("UPDATE ledger_periods SET status='CLOSED'"));const s=await f.snapshot();await f.post().expect(409);expect(await f.snapshot()).toEqual(s);await f.tenant(c=>c.query("UPDATE ledger_periods SET status='OPEN'"));await f.post().expect(201);});
 it('receipt fault rolls back new accounts, runs, journals, notifications, audits and counters',async()=>{const f=await fixture([3,1],false),s=await f.snapshot();await pool.query(`CREATE FUNCTION dividend_test_fail_receipt() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.response IS NOT NULL AND NEW.action='dividends.post' AND NEW.organization_id='${f.org}'::uuid THEN RAISE EXCEPTION 'synthetic dividend receipt failure'; END IF; RETURN NEW; END; $$`);await pool.query('CREATE TRIGGER dividend_test_fail_receipt BEFORE UPDATE ON financial_write_receipts FOR EACH ROW EXECUTE FUNCTION dividend_test_fail_receipt()');try{await f.post().expect(500);expect(await f.snapshot()).toEqual(s);}finally{await pool.query('DROP TRIGGER dividend_test_fail_receipt ON financial_write_receipts');await pool.query('DROP FUNCTION dividend_test_fail_receipt()');}await f.post().expect(201);});
 it('historical run without a receipt fails closed',async()=>{const f=await fixture();await f.post().expect(201);await f.tenant(async c=>{await c.query("SET LOCAL app.maintenance='on'");await c.query("DELETE FROM financial_write_receipts WHERE action='dividends.post'");});const s=await f.snapshot();await f.post().expect(409);expect(await f.snapshot()).toEqual(s);});
 it('incomplete receipt cannot create a new distribution',async()=>{const f=await fixture(),fingerprint=createHash('sha256').update(JSON.stringify({actorUserId:f.actor,period:f.period,amount:'1.15'})).digest('hex');await f.tenant(c=>c.query("INSERT INTO financial_write_receipts (organization_id,action,intent_key,fingerprint) VALUES ($1,'dividends.post',$2,$3)",[f.org,`dividend-year:${f.period}`,fingerprint]));const s=await f.snapshot();await f.post().expect(409);expect(await f.snapshot()).toEqual(s);});
 it('separate tenants post the same year independently',async()=>{const a=await fixture(),b=await fixture();await Promise.all([a.post().expect(201),b.post().expect(201)]);const sa=await a.snapshot(),sb=await b.snapshot();expect(sa.dividend_runs).toHaveLength(1);expect(sb.dividend_runs).toHaveLength(1);expect(sa.dividend_runs![0]!.organization_id).toBe(a.org);expect(sb.dividend_runs![0]!.organization_id).toBe(b.org);});
 it('concurrent deposit conserves savings balance and liability',async()=>{const f=await fixture();await Promise.all([f.post().expect(201),f.deposit(0.23).expect(201)]);for(const a of await f.reconcile()){expect(a.current_balance).toBe(a.movements);expect(a.current_balance).toBe(a.liability);}expect((await f.tenant(c=>c.query('SELECT current_balance FROM member_savings_accounts WHERE id=$1',[f.accounts[0]]))).rows[0].current_balance).toBe('1.09');});
 it('concurrent distinct years conserve balances without deadlock',async()=>{const f=await fixture();await Promise.all([f.post(1.15,'2026').expect(201),f.post(1.15,'2027').expect(201)]);expect((await f.snapshot()).dividend_runs).toHaveLength(2);for(const a of await f.reconcile()){expect(a.current_balance).toBe(a.movements);expect(a.current_balance).toBe(a.liability);}});
 it('account opening and dividend create one account concurrently',async()=>{const f=await fixture([1],false);await Promise.all([f.post(0.01).expect(201),request(app.getHttpServer()).post(`/api/v1/savings/member/${f.members[0]}/account`).set(f.auth).send({}).expect(201)]);const s=await f.snapshot();expect(s.member_savings_accounts).toHaveLength(1);expect(s.member_savings_accounts![0]!.current_balance).toBe('0.01');});
 it('large stored balance retains exact one-kobo credit',async()=>{const f=await fixture([1]);await f.tenant(c=>c.query("UPDATE member_savings_accounts SET current_balance='90000000000000000.01'"));await f.post(0.01).expect(201);const s=await f.snapshot();expect(s.member_savings_accounts![0]!.current_balance).toBe('90000000000000000.02');expect(s.savings_transactions![0]!.signed_amount).toBe('0.01');expect(s.savings_transactions![0]!.running_balance).toBe('90000000000000000.02');});
 it('overflow refuses with complete rollback',async()=>{const f=await fixture([1]);await f.tenant(c=>c.query("UPDATE member_savings_accounts SET current_balance='99999999999999999.99'"));const s=await f.snapshot();await f.post(0.01).expect(400);expect(await f.snapshot()).toEqual(s);});
 it('negative rounding drift refuses in preview and posting without effects',async()=>{const f=await fixture(Array(9).fill(1)),s=await f.snapshot();await request(app.getHttpServer()).get('/api/v1/dividends/preview?period=2026&amount=0.05').set(f.auth).expect(400);await f.post(0.05).expect(400);expect(await f.snapshot()).toEqual(s);});
});
